/**
 * Bundle the Edge Function sources for Deno (TASKS 2.6.3).
 *
 * The library under src/lib is written for Node's NodeNext resolution: `./x.js` specifiers
 * that point at `.ts` files. Deno resolves specifiers literally and finds no `.js` file, so
 * `supabase start` refused to bundle the function (CI 32790078875). esbuild understands
 * the NodeNext convention and writes one self-contained module per function to
 * supabase/functions/<name>/index.ts — the generated entrypoint config.toml names.
 *
 * What stays OUT of the bundle: the npm packages (`@supabase/supabase-js`, `zod`), which
 * Deno installs itself through the `npm:` mappings in supabase/functions/<name>/deno.json,
 * and `node:*` built-ins, which Deno provides. Bundling supabase-js would drag in Node
 * WebSocket shims that do not run on the edge runtime.
 *
 * No secret can enter the bundle: it is built from source only; every credential is read
 * from Deno.env at request time. `scripts/check-bundle.ts` asserts that on the output.
 */
import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { logger } from '../src/lib/logger.js';

const ROOT = join(import.meta.dirname, '..');

export const FUNCTIONS: readonly { readonly name: string; readonly entry: string }[] = [
  { name: 'chat', entry: 'src/functions/chat/index.ts' },
  // Stage 3 part 3 (FND-320): the memory page's write endpoint.
  { name: 'memory', entry: 'src/functions/memory/index.ts' },
  // Stage 3 part 4 (FND-330): the users page's write endpoint.
  { name: 'admin', entry: 'src/functions/admin/index.ts' },
];

const BANNER = [
  '// GENERATED by `npm run functions:bundle` from src/functions — do not edit, do not commit.',
  '// deno-lint-ignore-file',
  '// @ts-nocheck',
  '',
].join('\n');

export async function bundleFunction(name: string, entry: string): Promise<string> {
  const outfile = join(ROOT, 'supabase', 'functions', name, 'index.ts');
  const result = await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    target: 'esnext',
    mainFields: ['module', 'main'],
    external: ['@supabase/supabase-js', 'zod', 'node:*'],
    legalComments: 'none',
    logLevel: 'silent',
  });
  const output = result.outputFiles[0];
  if (output === undefined) {
    throw new Error(`esbuild produced no output for ${name}`);
  }
  await mkdir(dirname(outfile), { recursive: true });
  await writeFile(outfile, BANNER + output.text, 'utf8');
  return outfile;
}

async function main(): Promise<void> {
  for (const fn of FUNCTIONS) {
    const outfile = await bundleFunction(fn.name, fn.entry);
    logger.info('bundled edge function', { name: fn.name, outfile });
  }
}

main().catch((error: unknown) => {
  logger.error('bundle failed', { error });
  process.exitCode = 1;
});
